### ISSUE TITLE
编译运行崩溃了

### ISSUE THREAD

**Issue by iponkan** [blindmonk/WanArchitecture#1]
这个commit下载的 `修改studio4.2 kapt兼容问题
81de560
`
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at NetworkKt.request(Network.kt:21)@a05624b]){CompletedContinuation(result=Response{protocol=http/1.1, code=200, message=OK, url=https://www.wanandroid.com/hotkey/json}, cancelHandler=InvokeOnCancel[@93fe428], onCancellation=null, idempotentResume=null, cancelCause=null)}@6a88541. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
[trace.txt](https://github.com/blindmonk/WanArchitecture/files/6464816/trace.txt)

**Comment by blindmonk** [comment]
哥们你运气太好了，这个是kotlin协程的bug。
可以把Kotlin.coroutines中"1.3.9"升级为1.4.3 尝试下。

**Comment by iponkan** [comment]
> 哥们你运气太好了，这个是kotlin协程的bug。
> 可以把Kotlin.coroutines中"1.3.9"升级为1.4.3 尝试下。

好使了
